replicaCount: 1
image:
  repository: ghcr.io/nimrod-s-weather-app/weather-notifications-service # Docker image repository
  tag: 7c3bc7102e8ff1b1a3a7c5588ee76eb078505d3d # Image tag (can be overridden in the pipeline)
service:
  type: ClusterIP
  port: 8080
  targetPort: 5001
