replicaCount: 1
image:
  repository: ghcr.io/nimrod-s-weather-app/weather-service # Docker image repository
  tag: 1096665f7e2328d942b24f131ec85b891269d130 # Image tag (can be overridden in the pipeline)
service:
  type: ClusterIP
  port: 8080
  targetPort: 5001

KAFKA_BROKER: "kafka.weather-infra.svc.cluster.local:9092"
apiKey: "d61f6140b64e3fe3bf5ed1a2cf7a411c"