replicaCount: 1
image:
  repository: ghcr.io/nimrod-s-weather-app/weather-service # Docker image repository
  tag: addcf934800f816586d4f58b725fe94e93377d01 # Image tag (can be overridden in the pipeline)
service:
  type: ClusterIP
  port: 8080
  targetPort: 5001
