replicaCount: 1  

image:
  repository: ghcr.io/nimrod-s-weather-app/weather-notifications-service  # Docker image repository
  tag: 9326f0896dc636347849318b6e94fe5c0afad230  # Image tag (can be overridden in the pipeline)

service:
  type: ClusterIP  
  port: 8080  
  targetPort: 5001  

