replicaCount: 1
image:
  repository: ghcr.io/nimrod-s-weather-app/weather-notifications-service
  tag: b3f9f9121072f24028f0e86b71097c54a8a38591 # overridden in the pipeline
service:
  type: ClusterIP
  port: 8080
argocd:
  repoURL: "https://github.com/Nimrod-s-weather-app/weather-service.git"
  targetRevision: "master"
  path: "k8s"
  destinationNamespace: "weather-service"
