replicaCount: 1

image:
  repository: ghcr.io/nimrod-s-weather-app/weather-notifications-service
  tag: latest # overridden in the pipeline

service:
  type: ClusterIP
  port: 8080

argocd:
  repoURL: "https://github.com/Nimrod-s-weather-app/weather-service.git"
  targetRevision: "master"
  path: "k8s"
  destinationNamespace: "weather-service"
