apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: {{ .Release.Namespace }}  
spec:
  selector:
    app: weather-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  
      targetPort: {{ .Values.service.targetPort }}  
  type: {{ .Values.service.type }}  
