apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-service
spec:
  project: default
  source:
    repoURL: "https://github.com/Nimrod-s-weather-app/weather-service.git"
    targetRevision: master
    path: "charts"  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
